include('properties_preprocessed.lua') -- This file is generated by the setup script
include('utility.lua')

include('workspace.lua')

include('Projects/substance.lua')

group('Testing')
  include('Projects/tests.lua')